# Position Controllers ---------------------------------------
# gripper_controller:
#   type: effort_controllers/JointPositionController
#   joint: right_finger_joint
#   pid: {p: 10.0, i: 0.001, d: 0.1}
#   mimic_joints:
#     left_finger_joint_controller:
#       type: effort_controllers/JointPositionController
#       joint: left_finger_joint
gripper_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - right_finger_joint
  mimic_joints:
    - left_finger_joint
  gains:
    right_finger_joint: {p: 20.0, i: 0.1, d: 0.2}
    left_finger_joint: {p: 20.0, i: 0.1, d: 0.2}
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0.05
    gripper_finger_joint: {trajectory: 0.2, goal: 0.2}
  stop_trajectory_duration: 0.5
  state_publish_rate:  125
  action_monitor_rate: 10
